server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret: c3ByaW5nLXdlYi1ub3ZlbC1jaGFsbGVuZ2UtZXRmZi1zZWN1cml0eS1jaGFsbGVuZ2UtYWxwaGEtYmV0YS1jaGFybGUtZGVsdGEK
  expire-length: 10800000 # 1000 miliseconds * 60 seconds * 60 minutes * 3 hours

spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
  profiles:
    active: default
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.type: trace # sql binding 값 출력
